# Generated by Django 2.2.12 on 2022-01-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('bid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
