# Generated by Django 2.2.12 on 2022-01-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220120_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
