# Generated by Django 2.2.12 on 2022-01-21 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20220120_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 13, 19, 37, 669314, tzinfo=utc)),
        ),
    ]
