# Generated by Django 2.2.12 on 2022-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
