# Generated by Django 2.2.12 on 2022-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20220125_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='proba',
        ),
        migrations.AddField(
            model_name='user',
            name='watched',
            field=models.ManyToManyField(related_name='users', to='auctions.Bid'),
        ),
    ]
