# Generated by Django 2.2.12 on 2022-01-27 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20220127_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watched',
        ),
        migrations.AddField(
            model_name='bid',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
