# Generated by Django 2.2.12 on 2022-01-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220127_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist', to='auctions.Listing'),
        ),
    ]
