# Generated by Django 2.2.12 on 2022-01-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20220128_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.ManyToManyField(related_name='wins', to='auctions.Listing'),
        ),
    ]
